Added a binary mod to the URI.open method
onlyoffice-testing-robot/convert_service_testing pull request #63
Opened 2020-06-11 14:57 UTC by askonev

2020-06-11 15:00 UTC, ShockwaveNN commented
Again - why this needed

2020-06-11 15:02 UTC, ShockwaveNN requested changes

2020-06-11 15:02 UTC, ShockwaveNN commented on helpers/image_helper.rb
> +      binary_image = URI.open(URI.parse(url), 'r:binary').read
Uri.open(url).read will not close connection

https://stackoverflow.com/a/4217806/820501

2020-06-15 13:16 UTC, askonev commented
Why, when using the open method, activating the binmod?
 
The open method returns an object of the StreamIO class. The open method works with text data by default. When you try to read a binary file in text mode, data may be lost.

Why the construction is not recommended:

`URI.parse (url) .open ('r: binary') {| t | t.read}`

explained in this article:

https://stackoverflow.com/questions/17633293/ruby-binary-string-to-io

Why specifically the force-encoding method:

https://stackoverflow.com/questions/21614228/what-is-the-difference-between-encode-and-force-encoding-in-ruby

2020-06-15 14:32 UTC, ShockwaveNN commented
I think it's better not go into deep technical stuff, but just attach error or incorrect result which fix this PR

2020-06-15 14:33 UTC, ShockwaveNN approved these changes

2020-06-15 14:39 UTC, flaminestone approved these changes

2020-06-15 15:10 UTC, merged