Add unit test images_helper
onlyoffice-testing-robot/convert_service_testing pull request #69
Opened 2020-07-08 14:50 UTC by askonev

2020-07-08 14:58 UTC, flaminestone commented
Plese, can you add more information about pr to description of pr. Why only 2 tests? Why you choosed this sizes for images?

2020-07-08 15:03 UTC, ShockwaveNN requested changes

2020-07-08 15:03 UTC, ShockwaveNN commented on units/test_helpers/test_image_helper_spec.rb
> +    url_image = 'https://raw.githubusercontent.com/onlyoffice-testing-robot/convert_service_testing/feature/unit_test_image_helper/assets/4637.png'
I think this url will be not working after merge `feature/unit_test_image_helper` to master

You can attach those images as screenshot in any github comment field. Github will generate permalink for them and you can use those instead of attaching image directly to project

2020-07-08 15:55 UTC, flaminestone approved these changes

2020-07-09 08:37 UTC, ShockwaveNN approved these changes

2020-07-09 09:41 UTC, merged