Create unit_test.yml
onlyoffice-testing-robot/convert_service_testing pull request #70
Opened 2020-07-09 10:36 UTC by askonev

2020-07-09 11:30 UTC, ShockwaveNN requested changes

2020-07-09 11:30 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +on:
Can be replace on `on: [push]` as here:

https://github.com/onlyoffice-testing-robot/onlyoffice_logger_helper/blob/master/.github/workflows/ruby.yml#L2

Same meaning for our projects but shorted

2020-07-09 11:30 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
`uses: ruby/setup-ruby@v1`
Is better, since not specific commit, but specific verison

2020-07-09 11:30 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +
Without this empty line easier to read

2020-07-09 11:30 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +
Without this empty line easier to read

2020-07-09 12:24 UTC, flaminestone approved these changes

2020-07-09 12:34 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +      shell: bash
Is `shell: bash` line needed? I do not use it in mine workflows and everything seems fine

2020-07-09 12:35 UTC, ShockwaveNN requested changes

2020-07-09 12:35 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +      run: bundle install
Better use
```
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
```

This allow setup gems in parallel (great speedup) and retry on network failures)

Like here:
https://github.com/onlyoffice-testing-robot/onlyoffice_logger_helper/blob/master/.github/workflows/ruby.yml#L18

2020-07-09 12:35 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +      shell: bash
Is `shell: bash` line needed? I do not use it in mine workflows and everything seems fine

2020-07-10 09:17 UTC, ShockwaveNN requested changes
This comment about `bundle install` still actual

https://github.com/onlyoffice-testing-robot/convert_service_testing/pull/70/files#r452183910

2020-07-10 10:32 UTC, ShockwaveNN approved these changes

2020-07-10 10:33 UTC, merged